DROP DATABASE teamfounder;
CREATE DATABASE teamfounder;

USE teamfounder;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId NVARCHAR(255) NOT NULL UNIQUE,
    username NVARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    privilege INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS skill (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL UNIQUE,
    status BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userSkill (
    userId BIGINT NOT NULL,
    skillId BIGINT NOT NULL,
    PRIMARY KEY (userId, skillId),
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (skillId) REFERENCES skill(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS course (
    courseCode VARCHAR(6) PRIMARY KEY ,
    name VARCHAR(255) NOT NULL,
    professorId VARCHAR(255) NOT NULL,
    academicYear TINYINT NOT NULL,
    semester TINYINT NOT NULL,
    description TEXT,
    courseStatus TINYINT NOT NULL -- 'ACTIVE', 'INACTIVE', 'ARCHIVED'
);

CREATE TABLE IF NOT EXISTS announcement (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    importanceLevel TINYINT NOT NULL, -- 'TRIVIAL', 'MINOR', 'NORMAL', 'MAJOR', 'CRITICAL'
    courseCode VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (courseCode) REFERENCES course(courseCode) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invitation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    senderId BIGINT NOT NULL,
    receiverId BIGINT NOT NULL,
    courseCode VARCHAR(100) NOT NULL,
    message TEXT,
    status TINYINT DEFAULT 0 NOT NULL, -- 'PENDING', 'ACCEPTED', 'REJECTED'
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (receiverId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (courseCode) REFERENCES course(courseCode) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS enrollment (
    userId BIGINT NOT NULL,
    courseCode VARCHAR(6) NOT NULL,
    enrolledAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (userId, courseCode),
    FOREIGN KEY (userId) REFERENCES users(id),
    FOREIGN KEY (courseCode) REFERENCES course(courseCode)
);

CREATE TABLE IF NOT EXISTS announceReceipt (
    receiptId BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId BIGINT NOT NULL,
    courseCode VARCHAR(100) NOT NULL,
    announcementId BIGINT NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (courseCode) REFERENCES course(courseCode) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS teamConfiguration (
    configId BIGINT AUTO_INCREMENT PRIMARY KEY,
    courseCode VARCHAR(6) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    formationType BOOLEAN DEFAULT FALSE, -- 'SELF-SELECTED', 'RANDOM'
    status BOOLEAN DEFAULT FALSE, -- 'CLOSED', 'ONGOING'
    minSize TINYINT NOT NULL,
    maxSize TINYINT NOT NULL,
    startDate DATETIME NOT NULL,
    endDate DATETIME NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (courseCode) REFERENCES course(courseCode) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    course_code VARCHAR(6) NOT NULL,
    legit BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (course_code) REFERENCES course(courseCode) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_member (
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (team_id, user_id), -- Composite primary key: ensures a user is unique within a team
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);